# Generated by Django 5.2.10 on 2026-04-15 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOtchet',
            fields=[
                ('id_dataset', models.AutoField(primary_key=True, serialize=False)),
                ('familia', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('otchestvo', models.TextField(blank=True, null=True)),
                ('module', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('kurs', models.IntegerField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('date_begin', models.TextField(blank=True, null=True)),
                ('date_finish', models.TextField(blank=True, null=True)),
                ('head1', models.TextField(blank=True, null=True)),
                ('head2', models.TextField(blank=True, null=True)),
                ('ruc_pract', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_otchet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracType',
            fields=[
                ('id_prac_type', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'prac_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('otchet', 'Отчет по практике'), ('diplom', 'Дипломная работа'), ('coursework', 'Курсовая работа'), ('other', 'Другой тип')], max_length=50, verbose_name='Тип шаблона')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Файл шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'db_table': 'doc_template',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generated/', verbose_name='Сгенерированный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainSDS.datasetotchet', verbose_name='Отчет')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainSDS.doctemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'db_table': 'generated_document',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
